services:
  email-tool:
    build:
      context: .
      dockerfile: Dockerfile
    image: email-spoofing-tool:latest
    container_name: email-tool
    stdin_open: true
    tty: true
    volumes:
      # Mount deps directory to persist data
      - ./deps:/app/deps
    environment:
      - TERM=xterm-256color
    networks:
      - email-tool-net

networks:
  email-tool-net:
    driver: bridge